# Generated by Django 3.1.5 on 2021-01-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210118_1333'),
        ('api', '0002_auto_20201218_1626'),
    ]

    operations = [
    ]
