# Generated by Django 3.1.5 on 2021-01-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('api', '0003_merge_20210124_1614'),
    ]

    operations = [
    ]
